bot_prefix: "PREFIX"
token: "BOT_TOKEN"
application_id: "APPLICATION_ID"
dbhost: "DATABASE_HOSTENAME"
dbuser: "DATABASE_USERNAME"
dbpassword: "DATABASE_PASSWORD"
databasename: "DATABASE_NAME"
owners:
  - OWNER_ID
blacklist:
  - 000000000000000000
main_color: 0xD75BF4
error: 0xE02B2B
success: 0x42F56C
warning: 0xF59E42
info: 0x4299F5
maps_api_key: "MAPS_API_KEY"
imgflip_pass: "IMGFLIP_PASSWORD"
pipeline_token: "PIPELINE_TOKEN"
openapi_token: "OPENAPI_TOKEN"