on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp://us-dal-bots-03.ploxhost.com
        username: i0geejw6.f47a6a0d
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        port: 2053
