on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: na731.pebblehost.com
        username: pebblehost@colinwilson.dev.251416
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: DadBot/
        port: 21
